services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/expenses
    depends_on:
      - db
    ports:
      - '8000:8000'
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: unless-stopped
  
  bot:
    build: ./backend
    command: uv run bot.py
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      BUDGET_REMINDER_HOUR: ${BUDGET_REMINDER_HOUR:-9}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
